// import DetilsImg from "../Details/DetilsImg";
// import { useUpdateUser } from "../Profile/useUpdateUser";

// import { CiClock2 } from "react-icons/ci";
// import { IoIosText } from "react-icons/io";
// import {
//   FaBookmark,
//   FaHeart,
//   FaRegBookmark,
//   FaRegHeart,
//   FaStar,
// } from "react-icons/fa";
// const movieee = {
//   id: "tt1670345",
//   Plot: "An F.B.I. Agent and an Interpol Detective track a team of illusionists who pull off bank heists during their performances, and reward their audiences with the money.",
//   Type: "movie",
//   Year: "2013",
//   post: "https://m.media-amazon.com/images/M/MV5BMTY0NDY3MDMxN15BMl5BanBnXkFtZTcwOTM5NzMzOQ@@._V1_SX300.jpg",
//   Title: "Now You See Me",
//   Actors: "Jesse Eisenberg, Common, Mark Ruffalo",
//   Runtime: "115 min",
//   Director: "Louis Leterrier",
//   imdbRating: "7.2",
// };

// function MovieDet({ user, movie }) {
//   const { updateUser, isUpdating } = useUpdateUser();
//   if (isUpdating) return <p>xxx</p>;

//   const iswhachlist = JSON.stringify(user.watchlist).includes(
//     `${movie.imdbID}`
//   );
//   const isFav = JSON.stringify(user.fav).includes(`${movie.imdbID}`);

//   function handlerWatchlist() {
//     const newWhatch = iswhachlist
//       ? user.watchlist.filter((a) => a.id !== movie.imdbID)
//       : [...user.watchlist, { id: movie.imdbID, post: movie.Poster }];
//     console.log(newWhatch);

//     updateUser({ user, newWhatch });
//   }

//   function handerFav() {
//     const newFav = isFav
//       ? user.fav.filter((a) => a.id !== movie.imdbID)
//       : [
//           ...user.fav,
//           {
//             Actors: movie.Actors,
//             imdbRating: movie.imdbRating,
//             Plot: movie.Plot,
//             Director: movie.Director,
//             id: movie.imdbID,
//             post: movie.Poster,
//             Year: movie.Year,
//             Title: movie.Title,
//             Type: movie.Type,
//             Runtime: movie.Runtime,
//             Genre: movie.Genre,
//           },
//         ];
//     updateUser({ user, newFav });
//   }
//   return (
//     <>
//       <DetilsImg movie={movie} />
//       <div className=" xl:px-8 xl:mb-16 mb-6 pt-2 border-r    px-2 ">
//         <div className=" flex items-center gap-x-1 ">
//           <div className=" xl:text-2xl text-2xl  font-bold  mb-1  text-gray-950    ">
//             {movie.Title}
//           </div>{" "}
//           {/* <span className=" font-semibold text-gray-700">{movie.Year} </span> */}
//         </div>
//         <p className=" text-gray-500 text-sm mb-3   ">
//           <span className=" font-semibold text-gray-800">{movie.Year}</span> /
//           {movie.Genre} /{movie.Type}
//           {movie.totalSeasons && "/"}
//           <span className=" text-xs">{movie.totalSeasons}</span>
//           {movie.totalSeasons && "seasons"}
//         </p>
//         {/* icons */}
//         <div className=" flex items-center gap-x-10 mb-5  ">
//           <div className=" flex items-center ">
//             <div className=" inline-block      ">
//               <CiClock2 color=" #14213d " size={20} />
//             </div>
//             <p className=" text-gray-600 text-sm  inline-block       ">
//               {movie.Runtime}
//             </p>
//           </div>
//           <div className=" flex items-center">
//             <div className=" inline-block     ">
//               <IoIosText color="#14213d " size={20} />
//             </div>
//             <p className=" text-gray-600 text-sm  inline-block      ">
//               English
//             </p>
//           </div>
//           <div className=" flex items-center">
//             <div className=" inline-block     ">
//               <FaStar color=" #14213d " size={20} />
//             </div>
//             <p className=" text-gray-600 text-sm  inline-block      ">
//               {movie.imdbRating}
//             </p>
//           </div>
//         </div>
//         {/* icons */}
//         {/* about */}
//         <p className=" text-gray-800  mb-3  font-semibold  text-sm   ">
//           {" "}
//           <span className=" font-bold  text-base   text-gray-900">
//             About:
//           </span>{" "}
//           {movie.Plot}
//         </p>
//         {/* Director */}
//         <p className=" text-gray-800  mb-3  font-semibold  text-sm  ">
//           <span className=" font-bold  text-base  text-gray-900">
//             Director:
//           </span>{" "}
//           {movie.Director}
//         </p>
//         <p className="text-gray-800  mb-3  font-semibold  text-sm ">
//           <span className=" font-bold  text-base  text-gray-900">Actors:</span>
//           {movie.Actors}
//         </p>
//         <div className=" flex gap-x-2">
//           <button
//             disabled={isUpdating}
//             onClick={handlerWatchlist}
//             className="  flex items-center text-sm  gap-x-1  w-auto     text-center   p-2 font-medium text-white    border  bg-teal-950  "
//           >
//             {" "}
//             {iswhachlist ? (
//               <FaBookmark style={{ fontSize: "15px", color: "white" }} />
//             ) : (
//               <FaRegBookmark style={{ fontSize: "15px", color: "white" }} />
//             )}
//             <p className=" font-semibold ">
//               {iswhachlist ? " Remove" : "Ad To Watchlist"}
//             </p>
//           </button>
//           <button
//             onClick={handerFav}
//             className="  flex items-center gap-x-1  text-sm   w-auto  text-center   p-2 font-medium text-white    border  bg-teal-950  "
//           >
//             {" "}
//             {isFav ? (
//               <FaHeart style={{ fontSize: "15px", color: "white" }} />
//             ) : (
//               <FaRegHeart style={{ fontSize: "15px", color: "white" }} />
//             )}
//             <p className=" font-semibold ">{isFav ? "Remove" : "Favourite"} </p>
//           </button>
//         </div>
//       </div>
//     </>
//   );
// }

// export default MovieDet;

//   {
//     id: "tt7137906",
//     Plot: "Five teens from Harlem become trapped in a nightmare when they're falsely accused of a brutal attack in Central Park. Based on the true story.",
//     Type: "series",
//     Year: "2019",
//     post: "https://m.media-amazon.com/images/M/MV5BZmJjM2YzOWEtOTYxYi00YjhkLTliMzgtMTA2MTc0NDQ1MDM4XkEyXkFqcGdeQXVyODY5OTk4MA@@._V1_SX300.jpg",
//     Genre: "Biography, Crime, Drama",
//     Title: "When They See Us",
//     Actors: "Asante Blackk, Caleel Harris, Ethan Herisse",
//     Runtime: "296 min",
//     Director: "Ava DuVernay",
//     imdbRating: "8.9",
//   },
//   {
//     id: "tt0306414",
//     Plot: "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
//     Type: "series",
//     Year: "2002–2008",
//     post: "https://m.media-amazon.com/images/M/MV5BZmY5ZDMxODEtNWIwOS00NjdkLTkyMjktNWRjMDhmYjJjN2RmXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
//     Genre: "Crime, Drama, Thriller",
//     Title: "The Wire",
//     Actors: "Dominic West, Lance Reddick, Sonja Sohn",
//     Runtime: "59 min",
//     Director: "N/A",
//     imdbRating: "9.3",
//   },
//   {
//     id: "tt0060196",
//     Plot: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
//     Type: "movie",
//     Year: "1966",
//     post: "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
//     Genre: "Adventure, Western",
//     Title: "The Good, the Bad and the Ugly",
//     Actors: "Clint Eastwood, Eli Wallach, Lee Van Cleef",
//     Runtime: "178 min",
//     Director: "Sergio Leone",
//     imdbRating: "8.8",
//   },
//   {
//     id: "tt0050083",
//     Plot: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
//     Type: "movie",
//     Year: "1957",
//     post: "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
//     Genre: "Crime, Drama",
//     Title: "12 Angry Men",
//     Actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
//     Runtime: "96 min",
//     Director: "Sidney Lumet",
//     imdbRating: "9.0",
//   },
//   {
//     id: "tt0068646",
//     Plot: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
//     Type: "movie",
//     Year: "1972",
//     post: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Crime, Drama",
//     Title: "The Godfather",
//     Actors: "Marlon Brando, Al Pacino, James Caan",
//     Runtime: "175 min",
//     Director: "Francis Ford Coppola",
//     imdbRating: "9.2",
//   },
//   {
//     id: "tt0071562",
//     Plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
//     Type: "movie",
//     Year: "1974",
//     post: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Crime, Drama",
//     Title: "The Godfather Part II",
//     Actors: "Al Pacino, Robert De Niro, Robert Duvall",
//     Runtime: "202 min",
//     Director: "Francis Ford Coppola",
//     imdbRating: "9.0",
//   },
//   {
//     id: "tt0110912",
//     Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
//     Type: "movie",
//     Year: "1994",
//     post: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Crime, Drama",
//     Title: "Pulp Fiction",
//     Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
//     Runtime: "154 min",
//     Director: "Quentin Tarantino",
//     imdbRating: "8.9",
//   },
//   {
//     id: "tt0167260",
//     Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
//     Type: "movie",
//     Year: "2003",
//     post: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Action, Adventure, Drama",
//     Title: "The Lord of the Rings: The Return of the King",
//     Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
//     Runtime: "201 min",
//     Director: "Peter Jackson",
//     imdbRating: "9.0",
//   },
//   {
//     id: "tt0109830",
//     Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
//     Type: "movie",
//     Year: "1994",
//     post: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Forrest Gump",
//     Actors: "Tom Hanks, Robin Wright, Gary Sinise",
//     Runtime: "142 min",
//     Director: "Robert Zemeckis",
//     imdbRating: "8.8",
//   },
//   {
//     id: "tt8579674",
//     Plot: "April 6th, 1917. As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.",
//     Type: "movie",
//     Year: "2019",
//     post: "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg",
//     Genre: "Action, Drama, War",
//     Title: "1917",
//     Actors: "Dean-Charles Chapman, George MacKay, Daniel Mays",
//     Runtime: "119 min",
//     Director: "Sam Mendes",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt14330672",
//     Plot: "Just before the secession of South Sudan, a married former singer from the north seeks redemption for causing the death of a southern man by hiring his oblivious wife as her maid.",
//     Type: "movie",
//     Year: "2023",
//     post: "https://m.media-amazon.com/images/M/MV5BMGYzZWQwYzgtYzkzNy00YThkLTlmYzEtNWM5ZThhMDU1NjIxXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "Goodbye Julia",
//     Actors: "Eiman Yousif, Siran Riak, Nazar Goma",
//     Runtime: "120 min",
//     Director: "Mohamed Kordofani",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0119217",
//     Plot: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
//     Type: "movie",
//     Year: "1997",
//     post: "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Good Will Hunting",
//     Actors: "Robin Williams, Matt Damon, Ben Affleck",
//     Runtime: "126 min",
//     Director: "Gus Van Sant",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt5013056",
//     Plot: "Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.",
//     Type: "movie",
//     Year: "2017",
//     post: "https://m.media-amazon.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
//     Genre: "Action, Drama, History",
//     Title: "Dunkirk",
//     Actors: "Fionn Whitehead, Barry Keoghan, Mark Rylance",
//     Runtime: "106 min",
//     Director: "Christopher Nolan",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt2119532",
//     Plot: "World War II American Army Medic Desmond T. Doss, serving during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
//     Type: "movie",
//     Year: "2016",
//     post: "https://m.media-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_SX300.jpg",
//     Genre: "Biography, Drama, History",
//     Title: "Hacksaw Ridge",
//     Actors: "Andrew Garfield, Sam Worthington, Luke Bracey",
//     Runtime: "139 min",
//     Director: "Mel Gibson",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt1160419",
//     Plot: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
//     Type: "movie",
//     Year: "2021",
//     post: "https://m.media-amazon.com/images/M/MV5BMDQ0NjgyN2YtNWViNS00YjA3LTkxNDktYzFkZTExZGMxZDkxXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
//     Genre: "Action, Adventure, Drama",
//     Title: "Dune",
//     Actors: "Timothée Chalamet, Rebecca Ferguson, Zendaya",
//     Runtime: "155 min",
//     Director: "Denis Villeneuve",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0118799",
//     Plot: "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.",
//     Type: "movie",
//     Year: "1997",
//     post: "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Comedy, Drama, Romance",
//     Title: "Life Is Beautiful",
//     Actors: "Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini",
//     Runtime: "116 min",
//     Director: "Roberto Benigni",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt0816692",
//     Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
//     Type: "movie",
//     Year: "2014",
//     post: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Adventure, Drama, Sci-Fi",
//     Title: "Interstellar",
//     Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
//     Runtime: "169 min",
//     Director: "Christopher Nolan",
//     imdbRating: "8.7",
//   },
//   {
//     id: "tt0364569",
//     Plot: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
//     Type: "movie",
//     Year: "2003",
//     post: "https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg",
//     Genre: "Action, Drama, Mystery",
//     Title: "Oldboy",
//     Actors: "Choi Min-sik, Yoo Ji-tae, Kang Hye-jeong",
//     Runtime: "120 min",
//     Director: "Park Chan-wook",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt0102926",
//     Plot: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
//     Type: "movie",
//     Year: "1991",
//     post: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Crime, Drama, Thriller",
//     Title: "The Silence of the Lambs",
//     Actors: "Jodie Foster, Anthony Hopkins, Scott Glenn",
//     Runtime: "118 min",
//     Director: "Jonathan Demme",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt0268978",
//     Plot: "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
//     Type: "movie",
//     Year: "2001",
//     post: "https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTgtNzc5MzVjMDVmNjY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Biography, Drama, Mystery",
//     Title: "A Beautiful Mind",
//     Actors: "Russell Crowe, Ed Harris, Jennifer Connelly",
//     Runtime: "135 min",
//     Director: "Ron Howard",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt0454921",
//     Plot: "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career",
//     Type: "movie",
//     Year: "2006",
//     post: "https://m.media-amazon.com/images/M/MV5BMTQ5NjQ0NDI3NF5BMl5BanBnXkFtZTcwNDI0MjEzMw@@._V1_SX300.jpg",
//     Genre: "Biography, Drama",
//     Title: "The Pursuit of Happyness",
//     Actors: "Will Smith, Thandiwe Newton, Jaden Smith",
//     Runtime: "117 min",
//     Director: "Gabriele Muccino",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0253474",
//     Plot: "During the WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.",
//     Type: "movie",
//     Year: "2002",
//     post: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Biography, Drama, Music",
//     Title: "The Pianist",
//     Actors: "Adrien Brody, Thomas Kretschmann, Frank Finlay",
//     Runtime: "150 min",
//     Director: "Roman Polanski",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt0120689",
//     Plot: "A tale set on death row in a Southern jail, where gentle giant John possesses the mysterious power to heal people's ailments. When the lead guard, Paul, recognizes John's gift, he tries to help stave off the condemned man's execut...",
//     Type: "movie",
//     Year: "1999",
//     post: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
//     Genre: "Crime, Drama, Fantasy",
//     Title: "The Green Mile",
//     Actors: "Tom Hanks, Michael Clarke Duncan, David Morse",
//     Runtime: "189 min",
//     Director: "Frank Darabont",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt0111161",
//     Plot: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
//     Type: "movie",
//     Year: "1994",
//     post: "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "The Shawshank Redemption",
//     Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
//     Runtime: "142 min",
//     Director: "Frank Darabont",
//     imdbRating: "9.3",
//   },
//   {
//     id: "tt0120338",
//     Plot: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
//     Type: "movie",
//     Year: "1997",
//     post: "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Titanic",
//     Actors: "Leonardo DiCaprio, Kate Winslet, Billy Zane",
//     Runtime: "194 min",
//     Director: "James Cameron",
//     imdbRating: "7.9",
//   },
//   {
//     id: "tt0120815",
//     Plot: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
//     Type: "movie",
//     Year: "1998",
//     post: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
//     Genre: "Drama, War",
//     Title: "Saving Private Ryan",
//     Actors: "Tom Hanks, Matt Damon, Tom Sizemore",
//     Runtime: "169 min",
//     Director: "Steven Spielberg",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt2582846",
//     Plot: "Two teenage cancer patients begin a life-affirming journey to visit a reclusive author in Amsterdam.",
//     Type: "movie",
//     Year: "2014",
//     post: "https://m.media-amazon.com/images/M/MV5BNTVkMTFiZWItOTFkOC00YTc3LWFhYzQtZTg3NzAxZjJlNTAyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "The Fault in Our Stars",
//     Actors: "Shailene Woodley, Ansel Elgort, Nat Wolff",
//     Runtime: "126 min",
//     Director: "Josh Boone",
//     imdbRating: "7.7",
//   },
//   {
//     id: "tt3783958",
//     Plot: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
//     Type: "movie",
//     Year: "2016",
//     post: "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg",
//     Genre: "Comedy, Drama, Music",
//     Title: "La La Land",
//     Actors: "Ryan Gosling, Emma Stone, Rosemarie DeWitt",
//     Runtime: "128 min",
//     Director: "Damien Chazelle",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0338013",
//     Plot: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories for ever.",
//     Type: "movie",
//     Year: "2004",
//     post: "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg",
//     Genre: "Drama, Romance, Sci-Fi",
//     Title: "Eternal Sunshine of the Spotless Mind",
//     Actors: "Jim Carrey, Kate Winslet, Tom Wilkinson",
//     Runtime: "108 min",
//     Director: "Michel Gondry",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt0137523",
//     Plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
//     Type: "movie",
//     Year: "1999",
//     post: "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "Fight Club",
//     Actors: "Brad Pitt, Edward Norton, Meat Loaf",
//     Runtime: "139 min",
//     Director: "David Fincher",
//     imdbRating: "8.8",
//   },
//   {
//     id: "tt1798709",
//     Plot: "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
//     Type: "movie",
//     Year: "2013",
//     post: "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg",
//     Genre: "Drama, Romance, Sci-Fi",
//     Title: "Her",
//     Actors: "Joaquin Phoenix, Amy Adams, Scarlett Johansson",
//     Runtime: "126 min",
//     Director: "Spike Jonze",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0245429",
//     Plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.",
//     Type: "movie",
//     Year: "2001",
//     post: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Animation, Adventure, Family",
//     Title: "Spirited Away",
//     Actors: "Daveigh Chase, Suzanne Pleshette, Miyu Irino",
//     Runtime: "125 min",
//     Director: "Hayao Miyazaki",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt2582802",
//     Plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
//     Type: "movie",
//     Year: "2014",
//     post: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Drama, Music",
//     Title: "Whiplash",
//     Actors: "Miles Teller, J.K. Simmons, Melissa Benoist",
//     Runtime: "106 min",
//     Director: "Damien Chazelle",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt0180093",
//     Plot: "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
//     Type: "movie",
//     Year: "2000",
//     post: "https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "Requiem for a Dream",
//     Actors: "Ellen Burstyn, Jared Leto, Jennifer Connelly",
//     Runtime: "102 min",
//     Director: "Darren Aronofsky",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt4034228",
//     Plot: "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies.",
//     Type: "movie",
//     Year: "2016",
//     post: "https://m.media-amazon.com/images/M/MV5BMTYxMjk0NDg4Ml5BMl5BanBnXkFtZTgwODcyNjA5OTE@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "Manchester by the Sea",
//     Actors: "Casey Affleck, Michelle Williams, Kyle Chandler",
//     Runtime: "137 min",
//     Director: "Kenneth Lonergan",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0114369",
//     Plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
//     Type: "movie",
//     Year: "1995",
//     post: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Crime, Drama, Mystery",
//     Title: "Se7en",
//     Actors: "Morgan Freeman, Brad Pitt, Kevin Spacey",
//     Runtime: "127 min",
//     Director: "David Fincher",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt1853728",
//     Plot: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
//     Type: "movie",
//     Year: "2012",
//     post: "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
//     Genre: "Drama, Western",
//     Title: "Django Unchained",
//     Actors: "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio",
//     Runtime: "165 min",
//     Director: "Quentin Tarantino",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt7286456",
//     Plot: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
//     Type: "movie",
//     Year: "2019",
//     post: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
//     Genre: "Crime, Drama, Thriller",
//     Title: "Joker",
//     Actors: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
//     Runtime: "122 min",
//     Director: "Todd Phillips",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt5311514",
//     Plot: "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
//     Type: "movie",
//     Year: "2016",
//     post: "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg",
//     Genre: "Animation, Drama, Fantasy",
//     Title: "Your Name.",
//     Actors: "Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita",
//     Runtime: "106 min",
//     Director: "Makoto Shinkai",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt5726616",
//     Plot: "In 1980s Italy, romance blossoms between a seventeen-year-old student and the older man hired as his father's research assistant.",
//     Type: "movie",
//     Year: "2017",
//     post: "https://m.media-amazon.com/images/M/MV5BNDk3NTEwNjc0MV5BMl5BanBnXkFtZTgwNzYxNTMwMzI@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Call Me by Your Name",
//     Actors: "Timothée Chalamet, Armie Hammer, Michael Stuhlbarg",
//     Runtime: "132 min",
//     Director: "Luca Guadagnino",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0113277",
//     Plot: "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a verbal clue at their latest heist.",
//     Type: "movie",
//     Year: "1995",
//     post: "https://m.media-amazon.com/images/M/MV5BYjZjNTJlZGUtZTE1Ny00ZDc4LTgwYjUtMzk0NDgwYzZjYTk1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Action, Crime, Drama",
//     Title: "Heat",
//     Actors: "Al Pacino, Robert De Niro, Val Kilmer",
//     Runtime: "170 min",
//     Director: "Michael Mann",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt8503618",
//     Plot: "The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.",
//     Type: "movie",
//     Year: "2020",
//     post: "https://m.media-amazon.com/images/M/MV5BNjViNWRjYWEtZTI0NC00N2E3LTk0NGQtMjY4NTM3OGNkZjY0XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_SX300.jpg",
//     Genre: "Biography, Drama, History",
//     Title: "Hamilton",
//     Actors: "Lin-Manuel Miranda, Phillipa Soo, Leslie Odom Jr.",
//     Runtime: "160 min",
//     Director: "Thomas Kail",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt0075314",
//     Plot: "A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.",
//     Type: "movie",
//     Year: "1976",
//     post: "https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Crime, Drama",
//     Title: "Taxi Driver",
//     Actors: "Robert De Niro, Jodie Foster, Cybill Shepherd",
//     Runtime: "114 min",
//     Director: "Martin Scorsese",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt6966692",
//     Plot: "A working-class Italian-American bouncer becomes the driver for an African-American classical pianist on a tour of venues through the 1960s American South.",
//     Type: "movie",
//     Year: "2018",
//     post: "https://m.media-amazon.com/images/M/MV5BYzIzYmJlYTYtNGNiYy00N2EwLTk4ZjItMGYyZTJiOTVkM2RlXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_SX300.jpg",
//     Genre: "Biography, Comedy, Drama",
//     Title: "Green Book",
//     Actors: "Viggo Mortensen, Mahershala Ali, Linda Cardellini",
//     Runtime: "130 min",
//     Director: "Peter Farrelly",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt0469494",
//     Plot: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.",
//     Type: "movie",
//     Year: "2007",
//     post: "https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "There Will Be Blood",
//     Actors: "Daniel Day-Lewis, Paul Dano, Ciarán Hinds",
//     Runtime: "158 min",
//     Director: "Paul Thomas Anderson",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt0264464",
//     Plot: "Barely 17 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.",
//     Type: "movie",
//     Year: "2002",
//     post: "https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
//     Genre: "Biography, Crime, Drama",
//     Title: "Catch Me If You Can",
//     Actors: "Leonardo DiCaprio, Tom Hanks, Christopher Walken",
//     Runtime: "141 min",
//     Director: "Steven Spielberg",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt0373889",
//     Plot: "With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.",
//     Type: "movie",
//     Year: "2007",
//     post: "https://m.media-amazon.com/images/M/MV5BOTA3MmRmZDgtOWU1Ny00ZDc5LWFkN2YtNzNlY2UxZmY0N2IyXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
//     Genre: "Action, Adventure, Family",
//     Title: "Harry Potter and the Order of the Phoenix",
//     Actors: "Daniel Radcliffe, Emma Watson, Rupert Grint",
//     Runtime: "138 min",
//     Director: "David Yates",
//     imdbRating: "7.5",
//   },
//   {
//     id: "tt1950186",
//     Plot: "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
//     Type: "movie",
//     Year: "2019",
//     post: "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_SX300.jpg",
//     Genre: "Action, Biography, Drama",
//     Title: "Ford v Ferrari",
//     Actors: "Matt Damon, Christian Bale, Jon Bernthal",
//     Runtime: "152 min",
//     Director: "James Mangold",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt1392190",
//     Plot: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.",
//     Type: "movie",
//     Year: "2015",
//     post: "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Action, Adventure, Sci-Fi",
//     Title: "Mad Max: Fury Road",
//     Actors: "Tom Hardy, Charlize Theron, Nicholas Hoult",
//     Runtime: "120 min",
//     Director: "George Miller",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt2380307",
//     Plot: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
//     Type: "movie",
//     Year: "2017",
//     post: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg",
//     Genre: "Animation, Adventure, Drama",
//     Title: "Coco",
//     Actors: "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
//     Runtime: "105 min",
//     Director: "Lee Unkrich, Adrian Molina",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt15398776",
//     Plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
//     Type: "movie",
//     Year: "2023",
//     post: "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg",
//     Genre: "Biography, Drama, History",
//     Title: "Oppenheimer",
//     Actors: "Cillian Murphy, Emily Blunt, Matt Damon",
//     Runtime: "180 min",
//     Director: "Christopher Nolan",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt9362722",
//     Plot: "Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a ...",
//     Type: "movie",
//     Year: "2023",
//     post: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
//     Genre: "Animation, Action, Adventure",
//     Title: "Spider-Man: Across the Spider-Verse",
//     Actors: "Shameik Moore, Hailee Steinfeld, Brian Tyree Henry",
//     Runtime: "140 min",
//     Director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
//     imdbRating: "8.6",
//   },
//   {
//     id: "tt0099685",
//     Plot: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
//     Type: "movie",
//     Year: "1990",
//     post: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
//     Genre: "Biography, Crime, Drama",
//     Title: "Goodfellas",
//     Actors: "Robert De Niro, Ray Liotta, Joe Pesci",
//     Runtime: "145 min",
//     Director: "Martin Scorsese",
//     imdbRating: "8.7",
//   },
//   {
//     id: "tt0097937",
//     Plot: "Christy Brown, born with cerebral palsy, learns to paint and write with his only controllable limb - his left foot.",
//     Type: "movie",
//     Year: "1989",
//     post: "https://m.media-amazon.com/images/M/MV5BYjdkNzA4MzYtZThhOS00ZDgzLTlmMDItNmY1ZjI5YjkzZTE1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Biography, Drama",
//     Title: "My Left Foot",
//     Actors: "Daniel Day-Lewis, Brenda Fricker, Alison Whelan",
//     Runtime: "103 min",
//     Director: "Jim Sheridan",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0088847",
//     Plot: "Five high school students meet in Saturday detention and discover how they have a great deal more in common than they thought.",
//     Type: "movie",
//     Year: "1985",
//     post: "https://m.media-amazon.com/images/M/MV5BOTM5N2ZmZTMtNjlmOS00YzlkLTk3YjEtNTU1ZmQ5OTdhODZhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Comedy, Drama",
//     Title: "The Breakfast Club",
//     Actors: "Emilio Estevez, Judd Nelson, Molly Ringwald",
//     Runtime: "97 min",
//     Director: "John Hughes",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0382932",
//     Plot: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
//     Type: "movie",
//     Year: "2007",
//     post: "https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg",
//     Genre: "Animation, Adventure, Comedy",
//     Title: "Ratatouille",
//     Actors: "Brad Garrett, Lou Romano, Patton Oswalt",
//     Runtime: "111 min",
//     Director: "Brad Bird, Jan Pinkava",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt0095765",
//     Plot: "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema's projectionist.",
//     Type: "movie",
//     Year: "1988",
//     post: "https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Cinema Paradiso",
//     Actors: "Philippe Noiret, Enzo Cannavale, Antonella Attili",
//     Runtime: "155 min",
//     Director: "Giuseppe Tornatore",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt1659337",
//     Plot: "Charlie, a 15-year-old introvert, enters high school and is nervous about his new life. When he befriends his seniors, he learns to cope with his friend's suicide and his tumultuous past.",
//     Type: "movie",
//     Year: "2012",
//     post: "https://m.media-amazon.com/images/M/MV5BZThjMmQ5YjktMTUyMC00MjljLWJmMTAtOWIzNDIzY2VhNzQ0XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
//     Genre: "Drama",
//     Title: "The Perks of Being a Wallflower",
//     Actors: "Logan Lerman, Emma Watson, Ezra Miller",
//     Runtime: "103 min",
//     Director: "Stephen Chbosky",
//     imdbRating: "7.9",
//   },
//   {
//     id: "tt1675434",
//     Plot: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
//     Type: "movie",
//     Year: "2011",
//     post: "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg",
//     Genre: "Biography, Comedy, Drama",
//     Title: "The Intouchables",
//     Actors: "François Cluzet, Omar Sy, Anne Le Ny",
//     Runtime: "112 min",
//     Director: "Olivier Nakache, Éric Toledano",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt2096673",
//     Plot: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
//     Type: "movie",
//     Year: "2015",
//     post: "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg",
//     Genre: "Animation, Adventure, Comedy",
//     Title: "Inside Out",
//     Actors: "Amy Poehler, Bill Hader, Lewis Black",
//     Runtime: "95 min",
//     Director: "Pete Docter, Ronnie Del Carmen",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt0108052",
//     Plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
//     Type: "movie",
//     Year: "1993",
//     post: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Biography, Drama, History",
//     Title: "Schindler's List",
//     Actors: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
//     Runtime: "195 min",
//     Director: "Steven Spielberg",
//     imdbRating: "9.0",
//   },
//   {
//     id: "tt0095327",
//     Plot: "A young boy and his little sister struggle to survive in Japan during World War II.",
//     Type: "movie",
//     Year: "1988",
//     post: "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
//     Genre: "Animation, Drama, War",
//     Title: "Grave of the Fireflies",
//     Actors: "Tsutomu Tatsumi, Ayano Shiraishi, Akemi Yamaguchi",
//     Runtime: "89 min",
//     Director: "Isao Takahata",
//     imdbRating: "8.5",
//   },
//   {
//     id: "tt1485796",
//     Plot: "Celebrates the birth of show business and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation.",
//     Type: "movie",
//     Year: "2017",
//     post: "https://m.media-amazon.com/images/M/MV5BMjI1NDYzNzY2Ml5BMl5BanBnXkFtZTgwODQwODczNTM@._V1_SX300.jpg",
//     Genre: "Biography, Drama, Musical",
//     Title: "The Greatest Showman",
//     Actors: "Hugh Jackman, Michelle Williams, Zac Efron",
//     Runtime: "105 min",
//     Director: "Michael Gracey",
//     imdbRating: "7.5",
//   },
//   {
//     id: "tt0045152",
//     Plot: "A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.",
//     Type: "movie",
//     Year: "1952",
//     post: "https://m.media-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
//     Genre: "Comedy, Musical, Romance",
//     Title: "Singin' in the Rain",
//     Actors: "Gene Kelly, Donald O'Connor, Debbie Reynolds",
//     Runtime: "103 min",
//     Director: "Stanley Donen, Gene Kelly",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt0449059",
//     Plot: "A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.",
//     Type: "movie",
//     Year: "2006",
//     post: "https://m.media-amazon.com/images/M/MV5BMTgzNTgzODU0NV5BMl5BanBnXkFtZTcwMjEyMjMzMQ@@._V1_SX300.jpg",
//     Genre: "Comedy, Drama",
//     Title: "Little Miss Sunshine",
//     Actors: "Steve Carell, Toni Collette, Greg Kinnear",
//     Runtime: "101 min",
//     Director: "Jonathan Dayton, Valerie Faris",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0795421",
//     Plot: "The story of a bride-to-be trying to find her real father told using hit songs by the popular 1970s group ABBA.",
//     Type: "movie",
//     Year: "2008",
//     post: "https://m.media-amazon.com/images/M/MV5BMTA2MDU0MjM0MzReQTJeQWpwZ15BbWU3MDYwNzgwNzE@._V1_SX300.jpg",
//     Genre: "Comedy, Musical, Romance",
//     Title: "Mamma Mia!",
//     Actors: "Meryl Streep, Pierce Brosnan, Amanda Seyfried",
//     Runtime: "108 min",
//     Director: "Phyllida Lloyd",
//     imdbRating: "6.5",
//   },
//   {
//     id: "tt2278388",
//     Plot: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
//     Type: "movie",
//     Year: "2014",
//     post: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
//     Genre: "Adventure, Comedy, Crime",
//     Title: "The Grand Budapest Hotel",
//     Actors: "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric",
//     Runtime: "99 min",
//     Director: "Wes Anderson",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt0093779",
//     Plot: "A bedridden boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.",
//     Type: "movie",
//     Year: "1987",
//     post: "https://m.media-amazon.com/images/M/MV5BYzdiOTVjZmQtNjAyNy00YjA2LTk5ZTAtNmJkMGQ5N2RmNjUxXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
//     Genre: "Adventure, Comedy, Family",
//     Title: "The Princess Bride",
//     Actors: "Cary Elwes, Mandy Patinkin, Robin Wright",
//     Runtime: "98 min",
//     Director: "Rob Reiner",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt0091042",
//     Plot: "A popular high school student, admired by his peers, decides to take a day off from school and goes to extreme lengths to pull it off, to the chagrin of his Principal, who'll do anything to stop him.",
//     Type: "movie",
//     Year: "1986",
//     post: "https://m.media-amazon.com/images/M/MV5BMDA0NjZhZWUtNmI2NC00MmFjLTgwZDYtYzVjZmNhMDVmOTBkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Comedy",
//     Title: "Ferris Bueller's Day Off",
//     Actors: "Matthew Broderick, Alan Ruck, Mia Sara",
//     Runtime: "103 min",
//     Director: "John Hughes",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0097165",
//     Plot: "Maverick teacher John Keating returns in 1959 to the prestigious New England boys' boarding school where he was once a star student, using poetry to embolden his pupils to new heights of self-expression.",
//     Type: "movie",
//     Year: "1989",
//     post: "https://m.media-amazon.com/images/M/MV5BOGYwYWNjMzgtNGU4ZC00NWQ2LWEwZjUtMzE1Zjc3NjY3YTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Comedy, Drama",
//     Title: "Dead Poets Society",
//     Actors: "Robin Williams, Robert Sean Leonard, Ethan Hawke",
//     Runtime: "128 min",
//     Director: "Peter Weir",
//     imdbRating: "8.1",
//   },
//   {
//     id: "tt0066921",
//     Plot: "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.",
//     Type: "movie",
//     Year: "1971",
//     post: "https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg",
//     Genre: "Crime, Sci-Fi",
//     Title: "A Clockwork Orange",
//     Actors: "Malcolm McDowell, Patrick Magee, Michael Bates",
//     Runtime: "136 min",
//     Director: "Stanley Kubrick",
//     imdbRating: "8.3",
//   },
//   {
//     id: "tt1285016",
//     Plot: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea and by the co-founder who was later squeezed out of the business.",
//     Type: "movie",
//     Year: "2010",
//     post: "https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Biography, Drama",
//     Title: "The Social Network",
//     Actors: "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
//     Runtime: "120 min",
//     Director: "David Fincher",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0080678",
//     Plot: "A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak. Behind his monstrous façade, there is revealed a person of kindness, intelligence and sophistication.",
//     Type: "movie",
//     Year: "1980",
//     post: "https://m.media-amazon.com/images/M/MV5BMDVjNjIwOGItNDE3Ny00OThjLWE0NzQtZTU3YjMzZTZjMzhkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
//     Genre: "Biography, Drama",
//     Title: "The Elephant Man",
//     Actors: "Anthony Hopkins, John Hurt, Anne Bancroft",
//     Runtime: "124 min",
//     Director: "David Lynch",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt0032553",
//     Plot: "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
//     Type: "movie",
//     Year: "1940",
//     post: "https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
//     Genre: "Comedy, Drama, War",
//     Title: "The Great Dictator",
//     Actors: "Charles Chaplin, Paulette Goddard, Jack Oakie",
//     Runtime: "125 min",
//     Director: "Charles Chaplin",
//     imdbRating: "8.4",
//   },
//   {
//     id: "tt6710474",
//     Plot: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
//     Type: "movie",
//     Year: "2022",
//     post: "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg",
//     Genre: "Action, Adventure, Comedy",
//     Title: "Everything Everywhere All at Once",
//     Actors: "Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis",
//     Runtime: "139 min",
//     Director: "Daniel Kwan, Daniel Scheinert",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0477348",
//     Plot: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
//     Type: "movie",
//     Year: "2007",
//     post: "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
//     Genre: "Crime, Drama, Thriller",
//     Title: "No Country for Old Men",
//     Actors: "Tommy Lee Jones, Javier Bardem, Josh Brolin",
//     Runtime: "122 min",
//     Director: "Ethan Coen, Joel Coen",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt1130884",
//     Plot: "Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.",
//     Type: "movie",
//     Year: "2010",
//     post: "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
//     Genre: "Mystery, Thriller",
//     Title: "Shutter Island",
//     Actors: "Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo",
//     Runtime: "138 min",
//     Director: "Martin Scorsese",
//     imdbRating: "8.2",
//   },
//   {
//     id: "tt3281548",
//     Plot: "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.",
//     Type: "movie",
//     Year: "2019",
//     post: "https://m.media-amazon.com/images/M/MV5BY2QzYTQyYzItMzAwYi00YjZlLThjNTUtNzMyMDdkYzJiNWM4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
//     Genre: "Drama, Romance",
//     Title: "Little Women",
//     Actors: "Saoirse Ronan, Emma Watson, Florence Pugh",
//     Runtime: "135 min",
//     Director: "Greta Gerwig",
//     imdbRating: "7.8",
//   },
//   {
//     id: "tt0092593",
//     Plot: "A French boarding school run by priests seems to be a haven from World War II until a new student arrives. Occupying the next bed in the dormitory to the top student in his class, the two young boys begin to form a bond.",
//     Type: "movie",
//     Year: "1987",
//     post: "https://m.media-amazon.com/images/M/MV5BZmYxOTA5YTEtNDY3Ni00YTE5LWE1MTgtYjc4ZWUxNWY3ZTkxXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
//     Genre: "Drama, War",
//     Title: "Au revoir les enfants",
//     Actors: "Gaspard Manesse, Raphael Fejtö, Francine Racette",
//     Runtime: "104 min",
//     Director: "Louis Malle",
//     imdbRating: "8.0",
//   },
//   {
//     id: "tt3262342",
//     Plot: "In a story depicted in oil painted animation, a young man comes to the last hometown of painter Vincent van Gogh to deliver the troubled artist's final letter and ends up investigating his final days there.",
//     Type: "movie",
//     Year: "2017",
//     post: "https://m.media-amazon.com/images/M/MV5BMTU3NjE2NjgwN15BMl5BanBnXkFtZTgwNDYzMzEwMzI@._V1_SX300.jpg",
//     Genre: "Animation, Drama, Mystery",
//     Title: "Loving Vincent",
//     Actors: "Douglas Booth, Jerome Flynn, Robert Gulaczyk",
//     Runtime: "94 min",
//     Director: "DK Welchman, Hugh Welchman",
//     imdbRating: "7.8",
//   },
